### ISSUE TITLE
msbuild issues (with 2019 community installed)

### ISSUE THREAD

**Issue by Gareth-Jones-ZA** [fluffynuts/gulp-msbuild#1]
- toolsVersion to allow numbers that are in string format
- vs2019 community edition - when "current" / "auto" used
      - MSBuild auto-detection: using msbuild version '16.1.76.45076' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\bin'

**Comment by fluffynuts** [comment]
Thanks for reporting -- gulp-msbuild has been tested against the VS2019 Build Tools install. I'll install VS Community and give that a go too (:

**Comment by tl24** [comment]
I have similar issues with Visual Studio Professional 2019.  My MSBuild location is:
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin
and
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\amd64

**Comment by fluffynuts** [comment]
@tl24 is this still an issue with the latest gulp-msbuild (0.6.2) for you? this particular issue was raised some time ago by a co-worker at my request, to remind me to sort this out and it's working fine for us at our CI with the above paths. If it's not working for you with 0.6.2, I'd like to know so I can investigate further. Since installing visual studio is arduous at best (and I should probably do this in a vm to avoid interference from my installations), I'd like to know for sure that it's still an issue before tackling all of that.

As far as I know gulp-msbuild also works with the vs2019 Build Tools installer, so if it's just Professional causing issues, that would help me to narrow it down a bit.

**Comment by Ubernt** [comment]
Hello @fluffynuts 
I'm still experiencing issues with Visual Studio 2019 Professional and with MSBuild Tools 2019:
 Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\15.0\Bin\amd64\MSBuild.exe ENOENT

**Comment by fluffynuts** [comment]
Closing as this appears to work with 2019 from my testing.
