### ISSUE TITLE
Doesnt seem to be working with Gulp 4

### ISSUE THREAD

**Issue by ChrisLang** [fluffynuts/gulp-msbuild#8]
The setup notes could be better, its very unclear how this is working as well. Some screenshots and or a demo would be nice. I'm assuming this project is dead?

**Comment by fluffynuts** [comment]
Hi @ChrisLang 

No, this project isn't dead, but gulp devs have made it very clear that they consider gulp-msbuild to be "not the way". Gulp4 is a radical departure from gulp 3, so that doesn't make it any easier.

I use this from within https://github.com/fluffynuts/zarro which provides a gulp 3-4 translation layer. If you're interested in using that, let me know - I can provide some guidance. An example repo you can look at if you like is https://github.com/fluffynuts/NExpect/. Zarro is largely driven by environment variables, which means that, more often than now, you don't actually have to write any gulp task code to build & test your .net projects.

If there's enough interest in gulp 4 support, I could have a look at it - I literally took over maintenance of this project because I use it for (daily) .net builds, but since that's all wrapped up in the sugar of zarro, I don't have to (personally) care about the great gulp 3-4 debacle. Which doesn't mean it's not of interest to others - it just means it's not high on my list of things to do (:

**Comment by viceice** [comment]
It works fo me with gulp v4 since a long time, see https://github.com/visualon/mathjax-sp

**Comment by fluffynuts** [comment]
@ChrisLang there are docs in the README and @viceice 's example at https://github.com/visualon/mathjax-sp/blob/main/gulpfile.js is quite easy to follow. Closing as resolved.
